### ISSUE TITLE
Documentation on Plugin API

### ISSUE THREAD

**Issue by dubcanada** [peteboere/css-crush#57]
Hello,

It's pretty easy to read the current plugins and get an general sense for what you need to do to build a plugin, but it would be nice to have documentation on it.

**Comment by losttheplot** [comment]
Hi; great project, but how do you instal or initiate a plugin, please? Also, how do you set an option? Neither of these attempts work - what should I do please?
```
<?php
require_once 'crush/CssCrush.php';
csscrush_set('options', array('minify'=>'false')); // this has no effect.
csscrush_set('config', array('plugins'=>'loop')); // this is a wild guess at how to initiate a plugin.
?>
```

**Comment by losttheplot** [comment]
OK, so you initialise one or more plugins as follows:
```
require_once 'crush/CssCrush.php';
csscrush_set('options', array('minify'=>'false'));
csscrush_set('options', array('plugins'=>'loop, colour'));
```
But what was throwing me is that the minify setting above is having no effect on the output i.e. the resultant css file is minified, despite csscrush_get('options', 'minify') showing as 'false'.

**Comment by peteboere** [comment]
`csscrush_set()` is for setting defaults, it's better to pass in the options you want when you're calling one of the compile functions:

    echo csscrush_tag('styles.css', $options);

**Comment by losttheplot** [comment]
Oh I see, thank you, although this still does not un-minify the output, so I'm obviously not getting it right with either of these attempts:
```
echo csscrush_tag('css/styles_crush.css', array('minify'=>'false'));
echo csscrush_tag('css/styles_crush.css', array('options'=> array('minify'=>'false')));
```

**Comment by peteboere** [comment]
echo csscrush_tag('css/styles_crush.css', array('minify'=>'false'));

Is the correct way, but it works for me...

**Comment by losttheplot** [comment]
This is exactly what I'm using, but the output is one solid block of css text i.e. not minified. Ho hum! ...not the end of the world tho'. Thanks :)
```
require_once 'crush/CssCrush.php';
csscrush_set('options', array('plugins'=> array('color', 'loop')));
$css_tag = csscrush_tag('css/styles_crush.css', array('minify'=>'false'));
```

**Comment by peteboere** [comment]
Ah, `false` should be the keyword, not a string

````php
$css_tag = csscrush_tag('css/styles_crush.css', array('minify'=> false)); 
````

**Comment by losttheplot** [comment]
Ah, yes, that's better. Thank you :)

I'm very impressed with css-crush; specifically the plugins such as the ability to create colour keywords.
