### ISSUE TITLE
@extend only seems to work from current file

### ISSUE THREAD

**Issue by coatesap** [peteboere/css-crush#69]
Hi, can you confirm whether @extend only works on declarations in the current file?

The classic example that I can't seem to get to work would be:

    @import "bootstrap.css";

    #nav-main {
        ul {
            @extend .nav;
            @extend .navbar-nav;
        }
    }

**Comment by peteboere** [comment]
It works cross file, though you can't extend a rule enclosed in a media query and expect predictable results.

Which I'm guessing is what is happening in your example since bootstrap uses media queries extensively.
