### ISSUE TITLE
import using set variables?

### ISSUE THREAD

**Issue by unetics** [peteboere/css-crush#70]
Is this posable? could it be?
for example:
@set {nav:greenNav;}
@import "sections/$(nav).css";
or
@set {nav:@import "sections/greenNav.css";}
$(nav);

**Comment by peteboere** [comment]
Nope, unfortunately because variables are global and are dealt with after all imports have been resolved.

Not sure what you're trying to do but an @ifset directive might help you:
````css
@ifset nav { @import "nav.css" }
@ifset not nav { @import "no-nav.css" }
````

**Comment by unetics** [comment]
thanks for taking the time to reply there is no ifset equals function either is there?

@ifset nav = default { @import "nav.css" }
@ifset nav = green { @import "green.css" }
