### ISSUE TITLE
calc() is not vendor prefixed

### ISSUE THREAD

**Issue by croxton** [peteboere/css-crush#79]
Before processing:

    .title {
        height: calc(80vh - 138px);
    }

After processing with CSS Crush: 

    .title {
        height: calc(80vh - 138px);
        height: calc(80vh - 138px);
        height: calc(80vh - 138px);
    }

The problem is in `aliases.ini`...

    [functions]

        ; Calc.
        calc[] = -webkit-calc
        calc[] = -moz-calc

... which should be:

    [functions.calc]

        ; Calc.
        calc[] = -webkit-calc
        calc[] = -moz-calc

This yields the expected output:

    .title {
        height: -webkit-calc(80vh - 138px);
        height: -moz-calc(80vh - 138px);
        height: calc(80vh - 138px);
    }

**Comment by peteboere** [comment]
Thanks for reporting @croxton,
Have pushed a fix, please close this issue if it works for you now.
