### ISSUE TITLE
@importing from symlinked dir not working

### ISSUE THREAD

**Issue by biziclop** [peteboere/css-crush#80]
… because css-crush/lib/CssCrush/Importer.php applies `realpath()` on it, generating urls like this:
`src: url(../../../../../../../here/there/anywhere/fonts/open_sans/opensans-regular-webfont.eot);`
If I simply remove the realpath call, it works as expected:
`src: url(fonts/open_sans/opensans-regular-webfont.eot);`
Is it actually necessary to call realpath?

BTW, thank you for this great tool. :)

**Comment by peteboere** [comment]
Rooted urls (starting with a slash) are not rewritten so you could symlink below the document root.

There is also an option (rewrite_import_urls) to disable url rewriting entirely:
https://github.com/peteboere/css-crush/blob/master/docs/api/options.md

**Comment by biziclop** [comment]
Thank you for answering. Unfortunately these options didn't help (and you probably have better things to do), so I will figure out something else.

Anyway, here are the results using the different `rewrite_import_urls` options, if anyone is intererested:

Normal case:

    /docroot/css/fonts/comicneue.ttf

    /docroot/css/fonts/comicneue/comicneue.css
            @font-face { src: url('comicneue.ttf'); }

    /docroot/css/style-before-crush.css
            @import url("fonts/comicneue/comicneue.css");

    /docroot/css/style-after-crush.css
            /* good */
            @font-face { src: url('fonts/comicneue/comicneue.ttf'); }

Symlinked case, `rewrite_import_urls = true`:

    /common_css/fonts/comicneue.ttf

    /common_css/fonts/comicneue/comicneue.css
            @font-face { src: url('comicneue.ttf'); }

    /docroot/css/fonts --symlink--> /common_css/fonts

    /docroot/css/style-before-crush.css
            @import url("fonts/comicneue/comicneue.css");

    /docroot/css/style-after-crush.css
            /* bad, points above of docroot */
            @font-face { src: url('../../common_css/fonts/comicneue/comicneue.ttf'); }

Symlinked case, `rewrite_import_urls = 'absolute'`:

    /common_css/fonts/comicneue.ttf

    /common_css/fonts/comicneue/comicneue.css
            @font-face { src: url('comicneue.ttf'); }

    /docroot/css/fonts --symlink--> /common_css/fonts

    /docroot/css/style-before-crush.css
            @import url("fonts/comicneue/comicneue.css");

    /docroot/css/style-after-crush.css
            /* differently bad, points above of docroot */
            @font-face { src: url('/../common_css/fonts/comicneue/comicneue.ttf'); }

Symlinked case, `rewrite_import_urls = false`:

    /common_css/fonts/comicneue.ttf

    /common_css/fonts/comicneue/comicneue.css
            @font-face { src: url('comicneue.ttf'); }

    /docroot/css/fonts --symlink--> /common_css/fonts

    /docroot/css/style-before-crush.css
            @import url("fonts/comicneue/comicneue.css");

    /docroot/css/style-after-crush.css
            /* bad, the font is somewhere else */
            @font-face { src: url('comicneue.ttf'); }

Symlink + ed cases with absolute url do the same:
    /docroot/css/style-before-crush.css
            @import url("/css/fonts/comicneue/comicneue.css");
