### ISSUE TITLE
Result empty when using data url as background image

### ISSUE THREAD

**Issue by Luuc15** [peteboere/css-crush#82]
When css contains a background-image with a data url the script returns a blank result.
If you have a big css file the result will be just an empty string

Example:
`<?php 
$content      = 'a {   background-image: url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2aWV3Qm94PSIwIDAgNTM3Ljk4IDI4My40NiI+PGRlZnM+PHN0eWxlPi5jbHMtMXtmaWxsOnVybCgjTmFhbWxvb3NfdmVybG9vcF8xNyk7fS5jbHMtMntmaWxsOiMxZjY0YWU7fS5jbHMtM3tmaWxsOiNmZmY7fTwvc3R5bGU+PGxpbmVhckdyYWRpZW50IGlkPSJOYWFtbG9vc192ZXJsb29wXzE3IiB4MT0iMTQxLjczIiB5MT0iMjgzLjQ2IiB4Mj0iMTQxLjczIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSI+PHN0b3Agb2Zmc2V0PSIwIiBzdG9wLWNvbG9yPSIjMzEyNzgzIi8+PHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIjMTM5ZmRiIi8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PHRpdGxlPmxvZ28tZWxpcGxheTwvdGl0bGU+PGcgaWQ9IkxheWVyXzIiIGRhdGEtbmFtZT0iTGF5ZXIgMiI+PGcgaWQ9IkxhYWdfMSIgZGF0YS1uYW1lPSJMYWFnIDEiPjxjaXJjbGUgY2xhc3M9ImNscy0xIiBjeD0iMTQxLjczIiBjeT0iMTQxLjczIiByPSIxNDEuNzMiLz48cGF0aCBjbGFzcz0iY2xzLTIiIGQ9Ik0zODQuMTUsMTM1LjU4bDI4LjQ1LDBhNi40Miw2LjQyLDAsMCwwLS4xNi0xMi44NUgzOTAuNThzMC01NC4xNCwwLTU0LjIxYTcuNzEsNy43MSwwLDAsMC0xNS40MS4xOXMwLDU4LDAsNTguMUE5LDksMCwwLDAsMzg0LjE1LDEzNS41OFoiLz48cGF0aCBjbGFzcz0iY2xzLTIiIGQ9Ik00NzMuNTQsMjIwYTYuNDMsNi40MywwLDAsMCwzLjU4LTguMzZMNDUyLjcsMTUyLjIzYTksOSwwLDAsMC0xNi44MS0uOTRjLS4xMS4yNS0xNy41Niw0Mi44OC0yMy4wOCw1Ni4zNEgzOTAuNThzMC01NC4xNCwwLTU0LjIxYTcuNzEsNy43MSwwLDAsMC0xNS40MS4xOXMwLDU4LDAsNTguMWE5LDksMCwwLDAsOSw4Ljc2aDMzYTYuNDIsNi40MiwwLDAsMCw2LTRsNS43My0xNGgzMC42Mmw1LjczLDE0QTYuNDMsNi40MywwLDAsMCw0NzMuNTQsMjIwWm0tMzkuNDQtMzAuNCwxMC0yNC41MSwxMCwyNC41MVoiLz48cGF0aCBjbGFzcz0iY2xzLTIiIGQ9Ik01MzcuNDMsMTQ5LjYxYTYuODksNi44OSwwLDAsMC0xMi43Mi4xNWwtMjAuNjIsNTAuMzEtMjAuNjEtNTAuM2E2Ljg4LDYuODgsMCwxLDAtMTIuNzgsNS4xMmMuMTUuMzcsMTUsMzYuNzUsMjEuNDYsNTIuMzRhMTguNjgsMTguNjgsMCwwLDEtMTcuMzcsMjUuNTJoLS4xN2E2Ljg4LDYuODgsMCwwLDAtLjI1LDEzLjc0bC41NiwwaDBsLjE5LDBhMzIuMzEsMzIuMzEsMCwwLDAsMTEuNjktMi4zMWMxMS00LjQxLDE5LjczLTE0LjE0LDI1LjkyLTI4LjlsMjQuNzMtNjAuMzhBNi44NSw2Ljg1LDAsMCwwLDUzNy40MywxNDkuNjFaIi8+PHBhdGggY2xhc3M9ImNscy0yIiBkPSJNNDM0LDEzNS42YTcuNzEsNy43MSwwLDAsMCw3LjUxLTcuNzFjMC00Mi44NiwwLTU2LjY1LDAtNTkuNjVhNy43LDcuNywwLDAsMC0xNS4zOC40OWMwLDU5LjQtLjEsNTUuNzIsMCw1OS4zNUE3LjcyLDcuNzIsMCwwLDAsNDM0LDEzNS42WiIvPjxwYXRoIGNsYXNzPSJjbHMtMiIgZD0iTTQ0MS40OCw2OC4yM2MwLC4xLDAsLjIsMCwuM0M0NDEuNDksNjcuNTIsNDQxLjQ4LDY3LjA4LDQ0MS40OCw2OC4yM1oiLz48cGF0aCBjbGFzcz0iY2xzLTIiIGQ9Ik0zMTkuODQsMTM1LjU4bDM4Ljc0LDBhNi40Miw2LjQyLDAsMCwwLS4xNi0xMi44NUgzMjYuMjd2LTE4aDMyLjMxYTYuNDIsNi40MiwwLDAsMC0uMTYtMTIuODVIMzI2LjI3di0xOGgzMi4zMUE2LjQyLDYuNDIsMCwwLDAsMzU4LjQyLDYxSDMxOS42MmE5LDksMCwwLDAtOC43Niw5aDBzMCw1Ni43NCwwLDU2LjgxQTksOSwwLDAsMCwzMTkuODQsMTM1LjU4WiIvPjxwYXRoIGNsYXNzPSJjbHMtMiIgZD0iTTM0MywxNDUuODlzLTI0LjEzLDAtMjQuNjMsMGE3LjcxLDcuNzEsMCwwLDAtNy41MSw3LjcxaDB2NTkuMTZoMGMwLC4wNiwwLC4xMiwwLC4xOWE3LjcxLDcuNzEsMCwwLDAsMTUuNDEtLjE5aDBWMTg5LjYxSDM0M2EyMS44NiwyMS44NiwwLDAsMCwwLTQzLjcyWm0wLDMwLjg3SDMyNi4yN3YtMThIMzQzYTksOSwwLDAsMSwwLDE4WiIvPjxwYXRoIGNsYXNzPSJjbHMtMyIgZD0iTTE0MS43MywzOC45MkEyNS4yOSwyNS4yOSwwLDEsMCwxNjcsNjQuMjEsMjUuMzEsMjUuMzEsMCwwLDAsMTQxLjczLDM4LjkyWiIvPjxwYXRoIGNsYXNzPSJjbHMtMyIgZD0iTTIxMi40Miw5Ni42MmMtLjA3LS4yNC0uMi0uNDctLjI5LS43MWExNS40MiwxNS40MiwwLDAsMC0uODQtMi4wOCwxNS41NywxNS41NywwLDAsMC0xLjM5LTEuODgsMTUuNTUsMTUuNTUsMCwwLDAtMS4zOS0xLjg4aDBsMCwwYTE0LjcsMTQuNywwLDAsMC0yLTEuNjYsMTUuMzUsMTUuMzUsMCwwLDAtMS40Ny0uODhjLS4yMi0uMTItLjQ0LS4yNS0uNjctLjM2YTE1LjIzLDE1LjIzLDAsMCwwLTItLjgxbC0uMTIsMGExNS40NiwxNS40NiwwLDAsMC00LjYzLS43OGMtLjM4LDAtLjc0LjExLTEuMTEuMTRhMTUuNjMsMTUuNjMsMCwwLDAtMiwuMjRjLS4zOS4wOC0uNzYuMTYtMS4xNC4yN2ExNC43NSwxNC43NSwwLDAsMC0zLDEuMTJoMGExNS41MSwxNS41MSwwLDAsMC0xLjg4LDEuMzksMTUuNTcsMTUuNTcsMCwwLDAtMS44OCwxLjM5bC05LjQ3LDkuNDZhNC4yMiw0LjIyLDAsMCwxLS4zMy4zYy0uMjguMjgtLjU5LjUxLS44OC43OC0xLC45LTEuOTMsMS43OS0yLjk1LDIuNjEtLjIzLjE4LS40OC4zNC0uNzEuNTItMSwuODEtMi4xLDEuNi0zLjIsMi4zMi0uMi4xMy0uNDIuMjQtLjYzLjM3LTEuMTUuNzMtMi4zMSwxLjQzLTMuNSwyLjA2LS4xOC4wOS0uMzcuMTctLjU1LjI2LTEuMjQuNjMtMi41LDEuMjMtMy43OCwxLjc1bC0uNTguMmMtMS4yOS41MS0yLjU5LDEtMy45MiwxLjM4LS4yOC4wOC0uNTcuMTMtLjg1LjIxLTEuMjUuMzUtMi41MS42OC0zLjguOTMtLjU5LjEyLTEuMi4xNy0xLjguMjYtMSwuMTYtMiwuMzQtMywuNDNxLTIuMzguMjMtNC44MS4yM2gtLjE0cS0yLjQyLDAtNC44MS0uMjNjLTEtLjEtMi0uMjgtMy0uNDQtLjU4LS4wOS0xLjE4LS4xNC0xLjc1LS4yNi0xLjI5LS4yNS0yLjU1LS41OC0zLjgxLS45NC0uMjgtLjA4LS41Ni0uMTMtLjg0LS4yMS0xLjMzLS40LTIuNjMtLjg3LTMuOTItMS4zOGwtLjU4LS4yYy0xLjI5LS41Mi0yLjU0LTEuMTItMy43OC0xLjc1LS4xOC0uMDktLjM3LS4xNi0uNTUtLjI2LTEuMjEtLjY0LTIuMzktMS4zNC0zLjU0LTIuMDgtLjE5LS4xMi0uNC0uMjItLjU5LS4zNS0xLjEtLjcyLTIuMTYtMS41Mi0zLjIxLTIuMzMtLjIzLS4xOC0uNDctLjMzLS43LS41MS0xLS44Mi0yLTEuNy0yLjk1LTIuNjEtLjI5LS4yNy0uNTktLjUxLS44OC0uNzhhNC4yMiw0LjIyLDAsMCwxLS4zMy0uM2wtOS40Ny05LjQ2YTE1LjU3LDE1LjU3LDAsMCwwLTEuODgtMS4zOSwxNS41MSwxNS41MSwwLDAsMC0xLjg4LTEuMzloMGExNC43NSwxNC43NSwwLDAsMC0zLTEuMTJjLS4zOC0uMTEtLjc1LS4xOS0xLjE0LS4yN2ExNS42MywxNS42MywwLDAsMC0yLS4yNGMtLjM3LDAtLjc0LS4xNC0xLjExLS4xNGExNS40NywxNS40NywwLDAsMC00LjYzLjc4bC0uMTIsMGExNS4yMiwxNS4yMiwwLDAsMC0yLC44MWMtLjIzLjExLS40NC4yNC0uNjcuMzZhMTUuMzksMTUuMzksMCwwLDAtMS40Ny44OEExNC43NSwxNC43NSwwLDAsMCw3NSw5MGwwLDBoMGExNS41NSwxNS41NSwwLDAsMC0xLjM5LDEuODgsMTUuNTcsMTUuNTcsMCwwLDAtMS4zOSwxLjg4LDE1LjM3LDE1LjM3LDAsMCwwLS44NCwyLjA4Yy0uMDguMjQtLjIyLjQ3LS4yOS43MWExNS45MiwxNS45MiwwLDAsMC0uNTcsMi45NCwxNi42MSwxNi42MSwwLDAsMCwwLDMsMTYsMTYsMCwwLDAsLjU3LDIuOTRjLjA2LjE5LjE2LjM3LjIzLjU2QTE0LjEsMTQuMSwwLDAsMCw3NSwxMTJzMzUuMzEsMjYuMzYsNDQuMTgsNDMuNzhjMTMuNzcsMjcsNy4wOSw3MSw3LjA2LDczLjE0aDBhMTUuNTIsMTUuNTIsMCwwLDAsMTEuNTEsMTQuOTQsMTUuMzYsMTUuMzYsMCwwLDAsNCwuNmgwYTE1LjM2LDE1LjM2LDAsMCwwLDQtLjZBMTUuNTIsMTUuNTIsMCwwLDAsMTU3LjI4LDIyOWgwdjBjMC0yLjIxLTYuNy00Ni4xMSw3LjA2LTczLjEyQzE3My4yLDEzOC40MSwyMDguNTEsMTEyLDIwOC41MSwxMTJhMTQuMSwxNC4xLDAsMCwwLDMuNjgtNmMuMDYtLjE5LjE3LS4zNy4yMy0uNTZhMTYsMTYsMCwwLDAsLjU3LTIuOTQsMTYuNjEsMTYuNjEsMCwwLDAsMC0zQTE1LjkyLDE1LjkyLDAsMCwwLDIxMi40Miw5Ni42MloiLz48L2c+PC9nPjwvc3ZnPg=="); }';
                    $processed = csscrush_string($content);
                    echo $processed; ?>`

**Comment by peteboere** [comment]
Seems to work fine for me, copy/pasting what you have posted.

Do you have any other details about your setup? Platform, php version, latest css-crush version etc.

**Comment by Luuc15** [comment]
Platform: OSX 10.11.6 
PHP Version: 7.0.15
Css-Crush version: 2.4.0

Could it maybe have something todo with the line length?

**Comment by peteboere** [comment]
It looks like new php7 ini value `pcre.jit` is causing the issue, disabling it seems to do the trick.

```php
ini_set('pcre.jit', 0);
```

**Comment by Luuc15** [comment]
Thanks that did the trick!

**Comment by peteboere** [comment]
Workaround now in master
