### ISSUE TITLE
Dynamic @ifset variable inside loop

### ISSUE THREAD

**Issue by reardestani** [peteboere/css-crush#87]
It seems it doesn't work.

```
@set heading-1-color red;
@set heading-2-color green;

@for heading in 1, 2 {
    h#(heading) {
       @ifset heading-#(heading)-color { color: $(heading-#(heading)-color) }
    }
}
```

**Comment by reardestani** [comment]
It seems, moving `$this->resolveLoops();` to the beginning of `capture_phase0` (http://take.ms/jLrBr) will fix the issue but I am afraid it causes other issues.

**Comment by peteboere** [comment]
Related #83

**Comment by reardestani** [comment]
@peteboere Thanks for reply, yes, I got the possible fix from there.

You mean the issue is fixed? or you just reference the other issue.

Also another usage is following and it doesn't work even after moving `$this->resolveLoops(); `.

```
@set heading-1-color red;
@set heading-1-font-family arial;
@set heading-2-color green;

@for heading in 1, 2 {
    h#(heading) {
       @for property in color, font-family {
            @ifset heading-#(heading)-#(property) {
                #(property): $(heading-#(heading)-#(property));
            }
        }
    }
}
```

**Comment by reardestani** [comment]
@peteboere Any update on this and #88 

Thanks in advance,

**Comment by peteboere** [comment]
Hi @reardestani,

`@ifset` directives are akin to C-style preprocessor macros and are evaluated globally before loops are executed so cannot be used like a scripting `if` block in the way you are trying.

Generally speaking, CSS-Crush is simply a preprocessor (with plugins), and does not have scripting capabilities that you might be used to from products like Sass.

**Comment by reardestani** [comment]
@peteboere 

Thanks, I understand. We need to move our project to a powerful preprocessors.
