### ISSUE TITLE
Does `@abstract` support nesting?

### ISSUE THREAD

**Issue by biziclop** [peteboere/css-crush#89]
Hi, I tried the following thing below, but it doesn't seem to work with the child nested into the abstract rule. Is it a supported feature?

```
@abstract abstract {
  margin: 0;
  child {
    padding: 0;
  }
}

concrete {
  @extend abstract;
}
```
Result:
```
concrete {
  margin: 0;
}
```
Expected:
```
concrete {
  margin: 0;
}
concrete child {
  padding: 0;
}
```

**Comment by peteboere** [comment]
Unfortunately not.  Only `@fragment` supports nested blocks.
